### ISSUE TITLE
Docker documentation out of date?

### ISSUE THREAD

**Issue by matthijskooijman** [opensensorhub/osh-node-dev-template#3]
The README file still talks about a multi-stage docker file and just running `docker build` to get a working docker file, but the dockerfile itself seems to need a `version` build argument and expects a prebuilt version of OSH in the `build` subdirectory. If I just run the build, the build fails. It seems this was changed in 1310e889266dfd5e531a69a6fb642d698a8e7eca, but the README still documents the old situation.

So I wonder:
 - Is this repo (still?) the recommended to get OSH running in docker?
 - Why was this approach changed? A two-stage docker build that also builds the code before deploying, and not needing any dependencies in the host system, seems useful. Maybe to support the case where you are doing development and incremental builds in the host system anyway and just want to deploy in docker?

**Comment by nickgaray** [comment]
Updated the README.md and dockerfile to provide a clean way to build node and generate docker image containing deployed node.

**Comment by nickgaray** [comment]
@matthijskooijman I have updated the documentation and docker container building file.  I have tested in on Ubuntu 22.04 and it is building and starting correctly.

**Comment by matthijskooijman** [comment]
Apologies for my late reply, I diverted to other projects and only now found the time to continue with this again.

Thanks for looking into this, much appreciated.

I do not see any changes in the master branch, I'm assuming you made changes to the `3-docker-documentation-out-of-date` branch and forgot to merge to master (or wanted to wait for feedback first, maybe)?

I tried with that branch and the build now worked. I did get the same class major version error again, which I managed to resolve by completely removing openjdk-17 and openjdk-19 packages from my system (initially I just removed the jdk packages, but I also had to remove the jre packages), leaving openjdk-11 as the default java jdk and jre (I also have openjdk-8 still installed, but that seems to be ok).

As for the docker build docs, there are a few things which were not immediately clear. I think they are as follows:
 - For the `OSH-VERSION-FROM-build.gradle`, I was confused by`build.gradle`, since it lists 0.0.0. But I think this is just a dummy placeholder until an actual release is made? Since the actual file generated in `build/distributions` is literally `osh-node-0.0.0.zip`, so that's really what I should use, I guess. I do wonder: Is this really needed? Maybe the dockerfile could be modified to just use the present version if there is just one, or even inspect the `build.gradle` file to extract the version? Probably a future addition, though, for now it works with copy-paste ;-)
 - For the `-t` option, the docs only say `-t [repo]:[tag]`, and I'm just unfamiliar enough with docker to get confused about this, since I'm not planning to push to any repo. Reading the docs, I think the format is technically `repo_url/image:tag`, and you can omit the repo url and the tag (will be `latest`) as well, so maybe that's good to document?
 - For running the docker container, the mount paths includes a `[osh-node-path]` variable, which I *think* includes the version number looking at the dockerfile commands (though an `/opt/osh-node` symlink exists).
 - The README says you need to create an `osh` user in the host system, which violates the docker isolation a bit. Also, I think it is not strictly needed -  I think you can just ` sudo chown 4242:4242 data` in the host, without needing a username connected to the userid.
 - The docker run commands use `--mount`, is there any reason to not use `--volume`, which also allows mounting a local directory, or an autocreated named volume in docker's `/var/lib/docker/volumes` directory? I haven't tried this yet to see if it works, though.

In any case, I got a working webui running inside docker now, which is great. Next step is figuring out how OSH actually *works*, but that is of course out of scope for this issue :-)
